docs:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - README.*

automation:
  - changed-files:
    - any-glob-to-any-file:
      - .gitattributes
      - .github/**
      - .gitignore
      - .pre-commit-config.yaml
      - Makefile
      - _typos.toml
