name: Labeler
on: [pull_request]

permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on:
      - self-hosted-default

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml
