name: "Shared terraform module"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      REPO_ACCESS_TOKEN:
        description: "GitHub API token"
        required: false

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
      suggestions: "${{ github.event_name == 'pull_request' }}"
      runs-on: ${{ inputs.runs-on }}

  readme:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-readme.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit

  codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    with:
      is_fork: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
      runs-on: ${{ inputs.runs-on }}

  labels:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ github.event_name == 'push' || github.event.pull_request.state == 'open' }}
    steps:
      - uses: cloudposse/github-action-release-label-validator@v1

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() && (github.event_name == 'push' || github.event.pull_request.state == 'open') }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
    needs: [ terraform, readme, codeowners, labels ]

  release:
    needs: [ci]
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: ${{ inputs.runs-on }}
      publish: true
    secrets: inherit
