name: "Shared Terraform ChatOps"

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions's default behavior
    shell: bash -e -o pipefail {0}

jobs:
  access:
    if: ${{ github.event.issue.pull_request &&
            startsWith(github.event.comment.body, '/terratest') &&
            github.event.issue.state == 'open' }}
    uses: cloudposse/.github/.github/workflows/shared-access-controller.yml@main
    with:
      runs-on: ${{ inputs.runs-on }}
      permission: run_terratest
      user: ${{ github.event.comment.user.login }}

  test:
    uses: cloudposse-terraform-components/.github/.github/workflows/shared-terratest.yml@merge-queue
    needs: [access]
    with:
      pr_number: ${{ github.event.issue.number }}
      runs-on: ${{ inputs.runs-on }}
    

