name: "Shared terraform scheduled"

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  readme:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    environment: release
    steps:
      - uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.github-app.outputs.token }}

      - uses: cloudposse-github-actions/readme@add-labels-on-commit
        with:
          token: ${{ github.token }}
          readme_enabled: true
          banner_enabled: true
          validate_readme: true
          commit_method: 'pr'
          commit_push_options: '--force-with-lease'
        env:
          README_DEPS: docs/targets.md docs/terraform.md
          TERRAFORM_SOURCE_DIR: /src
