name: "Shared terraform module"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      REPO_ACCESS_TOKEN:
        description: "GitHub API token"
        required: false

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci-terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    name: "CI"
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
      suggestions: "${{ github.event_name == 'pull_request' }}"
      runs-on: ${{ inputs.runs-on }}

  ci-readme:
    # uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    name: "Readme"
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cloudposse-github-actions/readme@v0
        with:
          token: ${{ github.token }}
          readme_enabled: true
          banner_enabled: true
          validate_readme: true
          commit_method: 'commit'
          commit_push_options: '--force-with-lease'
        env:
          README_DEPS: docs/targets.md docs/terraform.md
          TERRAFORM_SOURCE_DIR: /src
#    with:
#      runs-on: ${{ inputs.runs-on }}
#    secrets: inherit

#  ci-codeowners:
#    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
#    name: "CI"
#    with:
#      is_fork: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
#      runs-on: ${{ inputs.runs-on }}
#    secrets:
#      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  ci-labels:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    name: "CI / Labels Validate"
    steps:
      - uses: cloudposse/github-action-release-label-validator@v1

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
    needs: [ ci-terraform, ci-readme, ci-labels ]

  auto-release:
    name: "Release"
    needs: [ci]
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: ${{ inputs.runs-on }}
      publish: true
    secrets: inherit
