name: "Terraform Component"
on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - main
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci-terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    name: "CI"
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
      suggestions: "${{ github.event_name == 'pull_request' }}"
      runs-on: '["ubuntu-latest"]'

  ci-readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    name: "Readme"
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: '["ubuntu-latest"]'
    secrets: inherit

  ci-codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    name: "CI"
    with:
      is_fork: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
      runs-on: '["ubuntu-latest"]'
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  ci-labels:
    runs-on: ["ubuntu-latest"]
    name: "CI / Labels Validate"
    steps:
      - uses: cloudposse/github-action-release-label-validator@v1

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
    needs: [ ci-terraform, ci-readme, ci-codeowners, ci-labels ]

  auto-release:
    name: "Release"
    needs: [ci]
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@main
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: '["ubuntu-latest"]'
      publish: true
    secrets: inherit
